### PR TITLE
Fix some traditional Chinese translations (zh_tw)

### PR DESCRIPTION
**Pull request by SiongSng**

### CODE REVIEW

**Comment by maxigator** [comment]
look #38 there should be a "common" field in the json

**Comment by SiongSng** [comment]
Ok, modified

**Comment by maxigator** [comment]
Line#64 to Line#70

**Comment by maxigator** [comment]
why did you remove 
"downloadjar": "下載JAR",
"alternatedownloads": "下載JAR手動安裝"

**Comment by SiongSng** [comment]
> why did you remove
"downloadjar": "下載JAR",
"alternatedownloads": "下載JAR手動安裝"

accidentally deleted the wrong

**Comment by thedocruby** [comment]
Thanks!

**Pull request merged**
