### PR TITLE
Grammar fix-up, langfield fix, clean-up

### PR DESCRIPTION
**Pull request by maxerium**
Cleaned up some grammar issues in the german locale, fixed the `screenshotsubheading` langfield in about.html so the locales will properly provide the translated string.

Also cleaned up the code to get rid of all .html extensions when browsing the page, as it is not needed on GitHub pages. See [this](https://rsp.github.io/gh-pages-no-extension/).

### CODE REVIEW

**Comment by edwloef** [comment]
The capital letters you corrected are also present in the English version, I would keep those. Otherwise this looks good to me!

(Shame on me for calling it der Mod instead of die Mod)

**Comment by maxerium** [comment]
Regarding the shadow text in [L#32](https://github.com/IrisShaders/irisshaders.github.io/pull/27/commits/e387c0b6a24cc2accd6c759e221ba9f62959adf9#diff-0c804e605640aaeee8ed59982109da53b15e76dc83ff9489e25445b9e7ddee4cR32); I mostly moved it there since it just seemed out of place in the entity part when it's describing an upside with shadow rendering.

The capitalization of certain words might be correct in english albeit it's not correct in German, explaining the changes from my end.

**Comment by edwloef** [comment]
Ah, I wasn't aware that title case wasn't a thing in German (regarding the capitalization), I've used it in school and nobody has complained. I agree with you about the shadow thing but I think it should stay as to not create significant differences between different languages.

**Comment by maxerium** [comment]
You're right, I've reverted the swap and it's back in place now.

**Comment by maxigator** [comment]
#13 and #27 already have some of this (remove HTML extension and subheading fix)

**Comment by maxerium** [comment]
Alright. Reverted all the changes that are in #13 and #23 and added the new `stillcurious` field to this PR.

**Comment by thedocruby** [comment]
Thanks!

**Pull request merged**
