### PR TITLE
Fixed every bad grammar/translations for Brazilian Portuguese

### PR DESCRIPTION
**Pull request by EmqsaGit**
Fixed bad grammar and translations that the previous translator let by... The way it was before makes me wonder if they used some sort of online translator 🤔

### CODE REVIEW

**Comment by EmqsaGit** [comment]
not sure if i should've created a pull request, but it seemed like a good idea

**Comment by IMS212** [comment]
Looks good to me so far

**Comment by EmqsaGit** [comment]
brazilian is not a language

**Comment by EmqsaGit** [comment]
misunderstood, if needed, rename to "brazilian"

**Comment by IMS212** [comment]
Thanks!

**Pull request merged**
